name: Accessibility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      myapp:
        image: node
        command: node server.js
        env:
          CI: true
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Run your build step here
      
      - name: Run accessibility tests
        run: pa11y-ci --config pa11y-ci.config.json http://localhost:3000
        env:
          PA11Y_RUN_ON_CI: true
