name: Accessibility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Start server
      run: yarn start &
      # The "&" character runs the command in the background.

    - name: Wait for server to start
      run: sleep 5s
      # This step gives the server time to start up.

    - name: Run accessibility tests
      run: yarn pa11y-ci
      env:
        CI: true

    - name: Upload pa11y report
      uses: actions/upload-artifact@v2
      with:
        name: pa11y-report
        path: ./pa11y-report/index.html
