name: Accessibility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      myapp:
        command: node index.js
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Run your build step here
      
      - name: Start server
        run: yarn start &
        env:
          MYAPP_URL: http://localhost:3000
      
      - name: Run accessibility tests
        run: pa11y-ci --config pa11y-ci.config.json $MYAPP_URL
        env:
          PA11Y_RUN_ON_CI: true
