name: 'Test Code for a11y issues'

on:  
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 1.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:3000
      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:3000
          
  pa11y-ci:
    runs-on: ubuntu-latest # This is the default, but it's here for clarity
    
    steps:
    - uses: actions/checkout@v1
    - uses: browser-actions/setup-chrome@latest
    - uses: Hesedi3l/pa11y-actions@v1
      with:
        start: start
        port: '3000'
  jest-axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test:jest