name: 'Test Code for a11y issues'

on:  
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pa11y:
    runs-on: ubuntu-latest # This is the default, but it's here for clarity
    
    steps:
    - uses: actions/checkout@v1
    - uses: browser-actions/setup-chrome@latest
    - uses: Hesedi3l/pa11y-actions@v1
      with:
        start: start
        port: '3000'
  jest-axe:
    runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest
        run: yarn test