name: 'Test Code for a11y issues'

on:  
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-a11y:
    runs-on: ubuntu-latest # This is the default, but it's here for clarity
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - run: yarn
      - run: npm run build --if-present
      - run: yarn start & npx wait-on http://localhost:3003
      - name: Run pa11y
          run:|
            npm install -g pa11y
            pa11y http://localhost:3003
