name: 'Test Code for a11y issues'

on:  
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pa11y:
    runs-on: ubuntu-latest # This is the default, but it's here for clarity
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile

      - run: yarn
      - run: npm run build --if-present
      - run: yarn start & npx wait-on http://localhost:3003
      - run: yarn test